version: '3.9'

services:
  nest-app:
    image: nest-app:latest
    ports:
      - '8000:8000'
    depends_on:
      - nest-db
    environment:
      - DATABASE_URL=mysql://fig:skwldnjs1!@nest-db:3306/nest-db

    networks:
      - nest-network

  nest-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=skwldnjs1!
      - MYSQL_USER=fig
      - MYSQL_PASSWORD=skwldnjs1!
    networks:
      - nest-network

networks:
  nest-network:
